### PR TITLE
Add ODBC support for SQL Server Adapter v7.0

### PR DESCRIPTION
**Pull request by lavika**
This pull request brings back ODBC support to activerecord-sqlserver-adapter gem which was revoked sometimes back, 

With every rails upgrade, we also try to upgrade activerecord-sqlserver-adapter and bring ODBC support back to the repo. 

This pull request contains total 13 commits out of which initial 9 commits are responsible for bring back ODBC and are being cherry-picked for every other upgrade as well. 
The other four commits are specific to version 7 and needs specific review 

Note - CI/CD checks are breaking here as there is a trouble installing ruby-odbc gem. The same has been happening in earlier releases as well. We have tested the changes internally and everything looks good. So, CI/CD checks can be ignored.

### CODE REVIEW

**Review by zeeamber — APPROVED** [review]
LGTM

**Comment by sukeerthiadiga** [comment]
Looks good to me.

**Comment by raj-sharan** [comment]
I think version should be 7.0.4.0.odbc in VERSION file

**Comment by raj-sharan** [comment]
Have you added this or automatically created in CHANGELOG.md file. I guess it is created with using a gem, not sure, but I see pull request link "https://github.com/cloudvolumes/activerecord-sqlserver-adapter/pull/17" is missing in this file.


## v7.0.4.0.odbc

#### Added

- ODBC restoration.

**Comment by smlsml** [comment]
Good work all, you should try to get the tests working and showcase this to the community. Obviously it is still needed, and with a little extra effort, it can be brought back to the gem officially!

**Comment by tojified** [comment]
> Good work all, you should try to get the tests working and showcase this to the community…

Good to hear from you! -toj

**Pull request merged**
