### PR TITLE
Restore ODBC changes from 5-2-stable-with-odbc to 6-0-stable-with-odbc

### PR DESCRIPTION
**Pull request by gupta-kanika-dev**
### Description:
Originally "activerecord-sqlserver-adapter" has dropped support for ODBC driver and supports only Tiny-TDS now. In order to restore this ODBC support back, we have made changes into "activerecord-sqlserver-adapter" earlier. 

### Changes made:
We have back ported the ODBC changes from "5-2-stable-with-odbc" into "6-0-stable-with-odbc" which is recent version of original "activerecord-sqlserver-adapter". This will ensure that we have latest changes along with ODBC restoration changes compatible with "activerecord-6.0"

### CODE REVIEW

**Review by sukeerthiadiga — APPROVED** [review]

**Review by lavika — APPROVED** [review]

**Comment by smlsml** [comment]
Can we try to get the CI tests to pass perhaps?

Also, would it be better to just use the master branch instead of sticking with 6.0? If nothing else, we should also catch-up this fork's master branch for good measure (in a separate PR).

**Comment by gupta-kanika-dev** [comment]
> Can we try to get the CI tests to pass perhaps?
> 

Hi @smlsml 
The CI tests are failing due to reason that 'ruby-odbc' gem installation is failing for github CI, please refer to https://github.com/cloudvolumes/activerecord-sqlserver-adapter/runs/6089634753?check_suite_focus=true

However  we have done following testing locally to ensure validity of changes done:
- The tests written for "activerecord-sqlserver-adapter" gem has been run and tested locally.
- The unit tests written for AVM has been tested on bamboo plan as well as on local using "activerecord-sqlserver-adapter" gem.

**Comment by sukeerthiadiga** [comment]
Yeah, that's right
As the patch now has dependency/requires ODBC, tests fail running on the default agent configured to run tests.

**Review by sukeerthiadiga — APPROVED** [review]

**Comment by sukeerthiadiga** [comment]
Regarding the master branch, upstream repo owners have renamed the master branch to main. And, we have created and made sure that we have pulled all the commits from the upstream main branch to our repo(forked) main branch.

On using the mainline branch, active-record-sqlserver-adapter community follows a rational versioning policy that tracks Rails.  This means 3.x version of Rails application should be using 3.x version of active-record-sqlserver. Similary, 6.x version of Rails should be using 6.x version of active-record-sqlserver.

**Pull request merged**
